name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Setup MySQL
      # You may pin to the exact commit or the version.
      # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
      uses: mirromutth/mysql-action@v1.1
      with:
        # The port of host
        host port: 3306
        # The port of container
        container port: 3306
        # --character-set-server - The character set of MySQL server
        character set server: utf8mb4
        # --collation-server - The character collation of MySQL server
        collation server: utf8mb4_general_ci
        # Version of MySQL to use
        mysql version: latest
        # MYSQL_ROOT_PASSWORD - root superuser password
        #mysql root password: 
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: goldenneighbour
        # MYSQL_USER - create the specified user with superuser power for created database
        #mysql user: # optional, default is 
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        #mysql password: # optional, default is 
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
